package:
  name: vacation-gatk
  version: "4.beta.6"

source:
  git_rev: 4.beta.6
  git_url: https://github.com/jason-weirather/gatk.git

build:
  number: 6

requirements:
  build:
    - java-jdk 8.*
  run:
    - java-jdk 8.*
    - r-essentials

about:
  home: https://github.com/jason-weirather/gatk/tree/conda
  license: BSD
  license_file: LICENSE.TXT
